fix(pauth): allow compiling with older toolchains
At the moment compiling the PAUTH test with an older toolchain results
in it complaining about the unsupported PAUTH instructions:

Error: selected processor does not support `paciasp'

This has been relaxed in later binutils releases, as those instructions
execute as NOP on older CPUs, so are safe to deploy everywhere.

Since those instructions are actually in the HINT space, provide wrapper
functions in assembly, and instantiate them using their "hint #x"
encodings, to make them compatible with any toolchain.

This allows compiling TFTF with the Ubuntu 20.04 provided toolchain.

Change-Id: I2fa15a5e7cef334777fd89d05aa534c63e1ddab9
Signed-off-by: Andre Przywara <andre.przywara@arm.com>