Revert "test(interrupts): add tests for interrupt routing"
This reverts commit 353a6cebde2586a866142f7dfbc6b8df644d03cd.

Reverting due to failure in Arm internal RMM CI which stops tagging of
rc0 for v2.9 release, Once the proper fix is found it will be taken
back either in next tag or after v2.9 release.

Failure log:
SMC_RMM_VERSION > 380000
RMM version is: 56.0
> Executing 'Realm payload multi CPU request'
SMC_RMM_VERSION > 380000
INFO: Booting
SMC_RMM_VERSION > 380000
INFO: Powering off
INFO: Booting
SMC_RMM_VERSION > 380000
INFO: Powering off
INFO: Booting
SMC_RMM_VERSION > 380000
INFO: Powering off
INFO: Booting
SMC_RMM_VERSION > 380000
INFO: Powering off
SMC_RMM_VERSION > 380000
INFO: Powering off
INFO: Booting
SMC_RMM_VERSION > 380000
INFO: Powering off
ERROR: Error: fffffffa
PANIC in file: spm/cactus/cactus_main.c line: 108

Change-Id: Id5179deb5324c1bd2fac41c7a030bf7e09a1c222