fix(include/lib/aarch64): fix access function for ID_AA64DFR[0-2]_EL1
Fix compilation error for older GCC versions
"Error: unknown or missing system register name at operand 2
-- `mrs x0,id_aa64dfr2_el1'"
Fix access function for ID_AA64PFR2_EL1, which is read only
register.

Change-Id: Id6a952213f5ba9f41b4d6d1e81a8cf847ef5c493
Signed-off-by: AlexeiFedorov <Alexei.Fedorov@arm.com>